### ISSUE TITLE
Implement and plot all figures

### ISSUE THREAD

**Issue by universmile** [natema/WorldDynamics.jl#32] opened 2022-09-16 11:28 UTC
At the moment, some standard figures from the historical runs of the book _Dynamics of Growth in a Finite World_ (1974) are implemented.
We should implement all of the figures and offer a side-by-side comparison to converge towards asserting that the current code is indeed in pair with the original.

**Comment by paulobruno** [comment] 2022-09-16 14:46
Duplicate of #4

**Closed by paulobruno** 2022-09-16 14:46 UTC
